name: CI - Build

on: 
  push:
    tags:
    - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  releases:
    name: release apk
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "11.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.0.1"

      - name: Pub Get Packages
        run: flutter pub get

      - name: Lint the app
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build apk
        run: flutter build apk --release

      - name: Build app bundle (aab)
        run: flutter build appbundle --release

      - name: Create github release
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: "build/app/outputs/flutter-apk/*.apk,build/app/outputs/bundle/release/*.aab"