name: CI - Build

on: 
  push:
    tags:
    - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  releases:
    name: release apk
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "11.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.0.1"
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - run: flutter build apk --release
      - uses: ncipollo/release-action@v1.10.0
        with:
         artifacts: "build/app/outputs/flutter-apk/*.apk"